[package]
name = "archive-tool"
version = "0.1.0"
edition = "2021"
publish = false
description = "A sample Rustolonia zip/tar explorer"

[dependencies]
avalonia = { path = "../../rust/avalonia" }
flate2 = "1"
tar = "0.4"
zip = { version = "2", default-features = false, features = ["deflate"] }

[workspace]
